#platform:ios, "9.0"


target 'MVVM_RACDemo' do
    
    pod 'YYText'
    
    pod 'Masonry'

    pod 'AFNetworking', '~>3.0'
    
    pod 'SDWebImage'
    
    pod 'ReactiveObjC', :git => 'https://github.com/ReactiveCocoa/ReactiveObjC'
    
end



